from sqlalchemy import Column, Integer, String, Float, Text, Boolean, Date
from .database import Base

class CharacterDB(Base):
    __tablename__ = "characters"

    charidentifier = Column(Integer, primary_key=True, autoincrement=True)
    identifier = Column(String(50), nullable=False, default="")
    steamname = Column(String(50), nullable=False, default="")
    group = Column(String(10), default="user")
    money = Column(Float, default=0.00)
    gold = Column(Float, default=0.00)
    rol = Column(Float, default=0.00)
    xp = Column(Integer, default=0)
    healthouter = Column(Integer, default=500)
    healthinner = Column(Integer, default=100)
    staminaouter = Column(Integer, default=100)
    staminainner = Column(Integer, default=100)
    hours = Column(Float, default=0)
    LastLogin = Column(Date, nullable=True)
    inventory = Column(Text, nullable=True)
    slots = Column(Float, default=35.0)
    job = Column(String(50), default="unemployed")
    joblabel = Column(String(255), default="job label")
    status = Column(String(140), default="{}")
    meta = Column(Text, default="{}")
    firstname = Column(String(50), default=" ")
    lastname = Column(String(50), default=" ")
    character_desc = Column(Text, default=" ")
    gender = Column(String(50), default=" ")
    age = Column(Integer, default=0)
    nickname = Column(String(50), default=" ")
    skinPlayer = Column(Text, nullable=True)
    compPlayer = Column(Text, nullable=True)
    compTints = Column(Text, nullable=True)
    jobgrade = Column(Integer, default=0)
    coords = Column(Text, default="{}")
    isdead = Column(Boolean, default=False)
    trust = Column(Integer, default=0)
    walk = Column(String(50), default="noanim")
    crafting = Column(Text, default='{"medical":0,"blacksmith":0,"basic":0,"survival":0,"brewing":0,"food":0}')
    info = Column(Text, default="{}")
    gunsmith = Column(Float, default=0.00)
    ammo = Column(Text, default="{}")
    discordid = Column(String(255), default="0")
    lastjoined = Column(Text, default="[]")
    ranchid = Column(Integer, default=0)
